[package]
name = "bcrust"
version = "0.1.0"
authors = ["Martin Dickson <martin.dickson34@gmail.com>"]
build = "build.rs"

[dependencies]
base64 = "0.10.0"
clap = "2.26.0"
libc = "0.2.0"
rand = "0.6.0"

[build-dependencies]
cc = "1.0"
